spring.application.name=gateway-service
server.port=8080

spring.main.web-application-type=reactive

jwt.secret=${JWT_SECRET}

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://auth-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=http://auth-service:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/user/**
spring.cloud.gateway.routes[1].filters[0]=JwtFilter

spring.cloud.gateway.routes[2].id=db-service
spring.cloud.gateway.routes[2].uri=http://db-service:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/db/**
spring.cloud.gateway.routes[2].filters[0]=JwtFilter